name: Build and Release Vanilla+ Radio

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract mod version
        id: version
        run: |
          # Извлекаем версию из gradle.properties (формат: mod_version=0.7-alpha)
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d= -f2 | tr -d "'\" ")
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_OUTPUT
          echo "Detected version: ${MOD_VERSION}"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build mod
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.MOD_VERSION }}"  # Тег: v0.7-alpha
          name: "Vanilla+ Radio ${{ steps.version.outputs.MOD_VERSION }}"  # Название релиза
          body: |
            ### Версия мода
            **${{ steps.version.outputs.MOD_VERSION }}**
            ### Скачать
            Основной файл: `radio-${{ steps.version.outputs.MOD_VERSION }}.jar`
          files: build/libs/*[!-dev].jar  # Исключает dev-сборки
          draft: false
          generate_release_notes: true
