name: Build and Release Vanilla+ Radio

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Добавляем шаг с установкой прав для gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Extract mod version
        id: version
        run: |
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d= -f2 | tr -d "'\" ")
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_OUTPUT
          echo "Detected version: ${MOD_VERSION}"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build mod
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.MOD_VERSION }}"
          name: "Vanilla+ Radio ${{ steps.version.outputs.MOD_VERSION }}"
          body: |
            ### Version
            **${{ steps.version.outputs.MOD_VERSION }}**
            ### Download
            Main file: `radio-${{ steps.version.outputs.MOD_VERSION }}.jar`
          files: build/libs/*[!-dev].jar
          draft: false
          generate_release_notes: true
