name: Build and Release Vanilla+ Radio

on:
  push:
    branches: [ main, master ]

# Добавляем разрешения для GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Необходимо для работы с тегами

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Extract mod version
        id: version
        run: |
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d= -f2 | tr -d "'\" ")
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_OUTPUT
          echo "Detected version: ${MOD_VERSION}"

      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v${MOD_VERSION}" -m "Release v${MOD_VERSION}"
          git push origin "v${MOD_VERSION}"
        env:
          MOD_VERSION: ${{ steps.version.outputs.MOD_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build mod
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.MOD_VERSION }}"
          name: "Vanilla+ Radio ${{ steps.version.outputs.MOD_VERSION }}"
          body: |
            ### Version
            **${{ steps.version.outputs.MOD_VERSION }}**
            ### Download
            Main file: `radio-${{ steps.version.outputs.MOD_VERSION }}.jar`
          files: build/libs/*[!-dev].jar
          draft: false
          generate_release_notes: true
